### ISSUE TITLE
python3 setup.py test failed with new libsodium 1.0.15 

### ISSUE THREAD

**Issue by sergiomb2** [saltstack/libnacl#105]
Hi, I'm one packager maintainer of libnacl on Linux Fedora, I got a report today that fails to build from the source with new libsodium 1.0.15  in rawhide [1]
It is an easy fix ? 

[1]
https://koji.fedoraproject.org/koji/buildinfo?buildID=977895
https://kojipkgs.fedoraproject.org//work/tasks/4814/22204814/build.log
```
libnacl (unittest.loader._FailedTest) ... ERROR
======================================================================
ERROR: libnacl (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: libnacl
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/builddir/build/BUILD/libnacl-1.5.2/libnacl/__init__.py", line 83, in <module>
    nacl = _get_nacl()
  File "/builddir/build/BUILD/libnacl-1.5.2/libnacl/__init__.py", line 81, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4, 
```

**Comment by thatch45** [comment]
Huh, this is odd, let me check....

**Comment by thatch45** [comment]
Try adding this patch:
https://github.com/saltstack/libnacl/commit/09e05149c9f82025c8229605a531ae49407d2f52

Does fedora not distribute a link to the current .so file?

**Comment by hegjon** [comment]
> Does fedora not distribute a link to the current .so file?

Only the -devel package provides a .so symlink without version: 

```
<mock-chroot> sh-4.4# ls -la /usr/lib64/libsodium.so*
lrwxrwxrwx. 1 root root     19 Oct  2 08:15 /usr/lib64/libsodium.so -> libsodium.so.23.0.0
lrwxrwxrwx. 1 root root     19 Oct  2 08:15 /usr/lib64/libsodium.so.23 -> libsodium.so.23.0.0
-rwxr-xr-x. 1 root root 351808 Oct  2 08:15 /usr/lib64/libsodium.so.23.0.0
<mock-chroot> sh-4.4# rpm -qf /usr/lib64/libsodium.so
libsodium-devel-1.0.15-1.fc28.x86_64
```

**Comment by thatch45** [comment]
ok, got it, that patch I referenced above should fix this up then. If you can confirm it works then I will push another release.

**Comment by hegjon** [comment]
I confirm that the patch fixed the build

**Comment by hegjon** [comment]
I tested against `python-libnacl-1.5.0-1.fc28.src.rpm`, but I assume that the fix will also work on 1.6.0

**Comment by sergiomb2** [comment]
I'm building now , if works I will push to Fedora rawhide

**Comment by thatch45** [comment]
Awesome, thanks! Sorry I was so late seeing this issue.

**Comment by sergiomb2** [comment]
yes it fixed the build , 
Thanks

**Comment by thatch45** [comment]
Ok, I am pushing a new release now with this fix so I will close this issue out

**Comment by sergiomb2** [comment]
I already built it for F27 and rawhide [1]
Thanks
[1]
https://koji.fedoraproject.org/koji/packageinfo?packageID=23470

**Comment by thatch45** [comment]
Awesome, glad to have this resolved
