### ISSUE TITLE
Could not locate nacl lib on Windows

### ISSUE THREAD

**Issue by clragon** [saltstack/libnacl#108]
![screenshot_1](https://user-images.githubusercontent.com/11785085/36989966-7f8301c6-20a3-11e8-87f0-651c20c988fc.png)

So basically this happens when I try to import the library... I tried installing it over pip3, and over setup.py

Is it just me or is there something wrong with it?

**Comment by thatch45** [comment]
libsodium needs to be installed separately. https://download.libsodium.org/libsodium/releases/
