### ISSUE TITLE
Consider pure python tweetnacl

### ISSUE THREAD

**Issue by thatch45** [saltstack/libnacl#12]
This is still just an idea, but it would allow for a pure python deployment of encrypted code to systems that do not have libsodium installed.

**Comment by thatch45** [comment]
Just fyi, this is under development and review

**Comment by jfindlay** [comment]
https://github.com/jfindlay/pyNaCl/

**Comment by thatch45** [comment]
I think that pyNACL is a great idea, if someone wants to get this merged into libnacl I am all on board. But I will ask that  PR gets opened
