### ISSUE TITLE
json.load encoding parameter was ignored in Python 3 and removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [saltstack/libnacl#120]
https://github.com/saltstack/libnacl/blob/74a21d27b90a208b0620304fc7f55c0cae54d789/libnacl/utils.py#L34

https://bugzilla.redhat.com/show_bug.cgi?id=1796024

**Comment by M5oul** [comment]
@thatch45, Hi, can you release a minor version with this fix to have Python3.9 support in projects using `libnacl` module?
Thank you.

**Comment by thatch45** [comment]
Yes, let me get this released
