### ISSUE TITLE
how to use a specific algorithm

### ISSUE THREAD

**Issue by rofl0r** [saltstack/libnacl#125]
i'd like to use e.g. crypto_box_curve25519xsalsa20poly1305 rather than just crypto_box so i know what i get.

**Comment by thatch45** [comment]
Does the aead module satisfy your needs? If not we would love to get another module specifically with crypto_box_curve25519xsalsa20poly1305

**Comment by thatch45** [comment]
I added classes not only for AEAD for specific modules, but also added a kx module allong for easy key exchange encryption using AEAD and can choose between chacha, xchacha and aesgcm
