### ISSUE TITLE
File saving to file-like objects

### ISSUE THREAD

**Issue by notpushkin** [saltstack/libnacl#40]
Use case: retrieve a key from server, then decrypt it. It could look like:

``` py
import requests
from Crypto.Cipher import AES
from filelike.wrappers import Decrypt
from libnacl.utils import load_key

enc = requests.get("http://example.com/keybackup.aes").raw # http://urllib3.readthedocs.org/
cipher = AES.new('abcdefgh')
dec = Decrypt(enc, cipher) # http://www.rfk.id.au/software/filelike/
key = load_key(dec)
```

And the same thing with saving.

Then, loading key from file would look like just `load_key(open("abc.key", 'r'))`. For a smooth transition we could check if  the first parameter is a string and open a file accordingly:

``` py
def load_key(fp, serial='json'):
    if not is_filelike(fp, 'r'):
        fp = open(fp, 'rb')
    # ...
```

**Comment by thatch45** [comment]
Sounds like a good idea! I will try to get it in!

**Comment by peter-conalgo** [comment]
Similar idea / approach:

For all objects that have a `save()` method, add a `for_json()` method. Then if [simplejson](https://simplejson.readthedocs.org) is used to serialize these objects, that function will be called when serializing any libnacl object.

See the [`for_json` argument](https://simplejson.readthedocs.org/en/latest/index.html?highlight=for_json#simplejson.JSONEncoder) to constructor of JSONEncoder.

Ideally, the `save()` member would move to a base class (or mixin) and it would just call `self.for_json()` too.

**Comment by sm-tradeboox** [comment]
Hello.

A "dump" method for key objects would be nice. 

You're already doing this prior to writing to a file.

We are looking into the possibility of directing the JSON to a socket, so we can use as a service and a dump method, though very simple to develop, would be better if implemented by you.

Thanks.

**Comment by peter-conalgo** [comment]
Just call `for_json()` on any key object. Returns  a dictionary.

**Comment by thatch45** [comment]
I will take a look at adding more in here for 1.5

**Comment by thatch45** [comment]
we got for_json() added a while back
