### ISSUE TITLE
why not pynacl?

### ISSUE THREAD

**Issue by steverweber** [saltstack/libnacl#41]
https://github.com/saltstack/libnacl
https://github.com/pyca/pynacl

pynacl seemed to be around longer.
why the rewrite?

**Comment by thatch45** [comment]
We tried to use pynacl but we could not get it to package properly and we had build and stability issues

**Comment by thatch45** [comment]
pynacl also had to be compiled making it less portable, we wanted a lib that we could get closer to a binary-less bootstrap. Hence #12. pynacl also came with a swath of deps, where libnacl has no deps outside of libsodium

**Comment by steverweber** [comment]
perhaps this blurb would be helpful on the readme page.
thanks for the info.

**Comment by thatch45** [comment]
Sure thing, that is a good idea :)

**Comment by thatch45** [comment]
773847bb7047438cebb6475ed9bc05a62793363b

Closed with a commit :)
