### ISSUE TITLE
(Not Issue) Question Regarding Dual Keys 

### ISSUE THREAD

**Issue by sm-tradeboox** [saltstack/libnacl#47]
Hello.

Thank you for the very well documented and finely crafted software. We are currently evaluating and considering for developing a security infrastructure.

I have a query regarding dual keys. Ed25519 keys can be converted to Curve25519 keys (http://doc.libsodium.org/advanced/ed25519-curve25519.html). Is this the same relationship between the signing -> encryption keys in dual keys?

Also, more out of curiosity, can we generate sub-keys from either Ed25519/Curve25519 keys?

Thanks very much.

Sam

**Comment by thatch45** [comment]
Thanks for asking and sorry I am behind on the reply here.
I am looking at getting this added in, since the actual raw keys are the same as far as bits are concerned.
When you say a sub key, do you mean the salsa key that is derived from the combination of keys?

**Comment by mumbleskates** [comment]
He may be referring to hierarchical child key derivation schemes, like BIP-32 standardizes for the secp256k1 curve. From what I can find, if this is what he seeks then it is [unlikely to be very safe to do yet](https://www.ietf.org/proceedings/interim-2017-cfrg-01/slides/slides-interim-2017-cfrg-01-sessa-bip32-ed25519-01.pdf). In fact, it's totally unclear whether this system is remotely compatible.

While deriving child secret keys from a parent secret is generally quite doable via hashing schemes, the point of these systems is usually to do it in such a way that third parties can derive corresponding child _public_ keys without knowledge of the parent secret key.

If that's really what's needed, you could do much worse than using secp256k1/BIP-32 wholesale in lieu of trying to wrangle equivalent function out of Ed25519.

**Comment by mumbleskates** [comment]
Also if you are asking whether Curve25519 keys can be converted back into Ed25519 keys, there appears to be [information loss](https://github.com/jedisct1/libsodium/blob/569778b517496861a3880e0e690973bf08a52e08/src/libsodium/crypto_sign/ed25519/ref10/keypair.c#L84-L86) when they are converted the first time, so I would hazard that this is probably not possible.

**Comment by thatch45** [comment]
Thanks @mumbleskates . I will close this out as I would prefer to keep the dual key with explicit keys for each scenario, thanks!
