### ISSUE TITLE
Support for Key type conversion

### ISSUE THREAD

**Issue by SmithSamuelM** [saltstack/libnacl#49]
In some applications it might be nice to not have to generate and manage both a signing key pair and an encryption key pair. Since Ed25519 and Curve25519 keys are birationally  equivalent , one can be converted into the other. Libsodium has a function,  to perform this conversion. The request to to expose this function in libnacl.

**Comment by SmithSamuelM** [comment]
src/libsodium/crypto_sign/ed25519/ref10/keypair.c    
int crypto_sign_ed25519_pk_to_curve25519(unsigned char *curve25519_pk,
+                                         const unsigned char *ed25519_pk)

**Comment by thatch45** [comment]
this is available as:
libnacl.crypto_sign_ed25519_pk_to_curve25519(ed2519_pk)
