### ISSUE TITLE
crypto_secretbox and crypto_secretbox_open don't check the length of the nonce or the key

### ISSUE THREAD

**Issue by oconnor663** [saltstack/libnacl#58]
If I run:

```python
import libnacl

# Empty message with the nonce and key having one byte each, instead of 24 and 32.
print(libnacl.crypto_secretbox(b'', b'\x00', b'\x00'))
```

I get output that's different every time I run it. Is this function reading uninitialized memory?

**Comment by thatch45** [comment]
Interesting, that function is just a direct call down to libsodium, so we don't do any checks in libnacl.

**Comment by oconnor663** [comment]
It looks like libnacl does validate the nonce and the key in the `crypto_box_*` functions. Any reason not to make the same effort for `crypto_secretbox`?
