### ISSUE TITLE
Question: does libnacl release the GIL?

### ISSUE THREAD

**Issue by lfdversluis** [saltstack/libnacl#79]
I would like to make things asynchronous, but if it doesn't release the GIL I would be only creating overhead when doing operations with libnacl on a separate thread.

I found nothing of the stuff mentioned in https://docs.python.org/3/c-api/init.html in the source code, so I assume it doesn't release it?

**Comment by thatch45** [comment]
no, libnacl does nothing with the GIL, threading in python will work as it always has. Also, libnacl is cpu bound, so even using async/await each operation will run synchronously, but this is the nature of cpu bound tasks.
