### ISSUE TITLE
sealed_boxes

### ISSUE THREAD

**Issue by steverweber** [saltstack/libnacl#81]
https://download.libsodium.org/doc/

sealed_boxes.html

I would like to add support in the salt nacl module for public key one way encryption.
This way people adding encrypted data to pillars wont need access to the private key that can decrypt.

```
salt-call nacl.pub_enc data="PASSWOTD" key="PUBKEY"
```

only the holder of the private key can render the pillar.

```
password: {{ salt['nacl.dec']('l8kuMoSUG5bStHO7Er08Wz/T10w8HDWfzgAIzbQ==') }}
```

**Comment by steverweber** [comment]
if https://github.com/jfindlay/pure_pynacl/issues/2 adds support for sealed_boxes then might migrate to it instead.

**Comment by thatch45** [comment]
Yes, I need to do some catch up!

**Comment by yagnik** [comment]
@thatch45 now that sealed boxes are merged, can we release a new version please and close this ?

**Comment by steverweber** [comment]
nice, I'll happly add sealedbox in saltstack `module.nacl`.

**Comment by yagnik** [comment]
@steverweber I can help, I also started working on that :)

**Comment by steverweber** [comment]
@yagnik Are you almost done? if not I might hammer out some code this morning.

**Comment by steverweber** [comment]
@yagnik fyi i'm about 1/2 done. I'll likely have a PR this afternoon.

**Comment by thatch45** [comment]
https://pypi.python.org/pypi/libnacl/1.5.1
Done :)
Sorry about the delay!

**Comment by thatch45** [comment]
Ok, new release has been announced
