### ISSUE TITLE
SecretBox is using an old libsodium crypto_secretbox API?

### ISSUE THREAD

**Issue by jootuom** [saltstack/libnacl#83]
As the documentation doesn't clearly specify whether libnacl's Secret Key Encryption is actually authenticated encryption or not, I started reading the source code and eventually noticed this:

[libnacl.secret.SecretBox](https://github.com/saltstack/libnacl/blob/master/libnacl/secret.py#L31) calls [libnacl.crypto_secretbox](https://github.com/saltstack/libnacl/blob/master/libnacl/__init__.py#L333) which calls the libsodium crypto_secretbox method...

The [libsodium documentation](https://download.libsodium.org/doc/secret-key_cryptography/authenticated_encryption.html) contains the following statement:

> The original NaCl `crypto_secretbox` API is also supported, albeit not recommended.
> 
> `crypto_secretbox()` takes a pointer to 32 bytes before the message, and stores the ciphertext 16 bytes after the destination pointer, the first 16 bytes being overwritten with zeros. 
> 
> `crypto_secretbox_open()` takes a pointer to 16 bytes before the ciphertext and stores the message 32 bytes after the destination pointer, overwriting the first 32 bytes with zeros.
> 
> The _easy and _detached APIs are faster and improve usability by not requiring padding, copying or tricky pointer arithmetic.

So, it appears libnacl can be made simpler/faster/more secure(?) by using the newer, simpler API. Unless compatibility with some other (older) implementations is required?

**Comment by thatch45** [comment]
Ahh, thank you for pointing this out, I will make this addition

**Comment by thatch45** [comment]
The easy routines have been added, I will update the docs to suggest using them
