### ISSUE TITLE
Documentation on signing is incorrect/misleading

### ISSUE THREAD

**Issue by brakhane** [saltstack/libnacl#84]
The documentation for "Signing and Verifying Messages" states:

> Please be advised that public key encrypted messages do not need to be signed, the nacl box construct verifies the validity of the sender.

However, the NaCl docs explicitly state:

> The crypto_box function is not meant to provide non-repudiation. On the contrary: the crypto_box function guarantees repudiability. A receiver can freely modify a boxed message, and therefore cannot convince third parties that this particular message came from the sender. The sender and receiver are nevertheless protected against forgeries by other parties. In the terminology of https://groups.google.com/group/sci.crypt/msg/ec5c18b23b11d82c, crypto_box uses "public-key authenticators" rather than "public-key signatures."
> 
> Users who want public verifiability (or receiver-assisted public verifiability) should instead use signatures (or signcryption). 

So the documentation is at least misleading; encrypted messages _need_ to be signed if they are intended to provide non-repudiation.

**Comment by thatch45** [comment]
Thanks, I will get this fixed

**Comment by thatch45** [comment]
looks like this was fixed a while ago

**Comment by brakhane** [comment]
https://libnacl.readthedocs.io/en/latest/topics/sign.html still has the original wording

**Comment by thatch45** [comment]
Thanks for the heads up, I was looking in the wrong place
