### ISSUE TITLE
allow generating secret key in public key encryption from seed

### ISSUE THREAD

**Issue by julianhille** [saltstack/libnacl#92]
Creating a `SecretKey` in `public.py` should be allowed by seed.

However i'd like to create a PR and implement that i'm unsure how to achieve that.

1. add a classmethod to the `SecretKey` model called something like `generate_from_seed`
2. add a function to public.py `generate_secret_key_from_seed`
3.  change signature of `__init__` method of the `SecretKey` and add seed as argument.
4.  always give a seed and create internally the right `sk` and `pk`

im mostly for 2.
1. im not a big fan of class methods in this case
3. has the issue that its not in all case backward compatible and is odd to give `sk` or `seed` or both or none of them. Not a good api and not easy to understand.
4.  would be backwards incompatible, but would be harmonize `Signer` and `SecretKey` creation.

What do you think?

**Comment by thatch45** [comment]
Wow, I am sorry I am so late in my reply. I bet you have moved on :(
I would agree that 2 would be good, to be honest I would say to do 2 and 3. But only if the seed to key generation is being done by libsodium of course :)

**Comment by thatch45** [comment]
If we have more demand here we can open this back up
