### ISSUE TITLE
Undocumented change of interface. 

### ISSUE THREAD

**Issue by marijnvriens** [saltstack/libnacl#94]
the d1b25c05cd94e94b8e89f63f60596bc56d524120 change which was included in the 1.5.1 release changed the interface when failing to decrypt a message from ValueError to CryptError. 

While I'm all for consistent interfaces, please do document these kinds of API changes in the Changelog, as they did unexpectedly affect our code base and will likely bite anybody who just updates to the latest patch-version of the code 1.5 branch.

**Comment by thatch45** [comment]
This change has been documented and re-documented in the 1.6.0 release
