### ISSUE TITLE
Undefined symbol: crypto_box_sealbytes

### ISSUE THREAD

**Issue by petebrowne** [saltstack/libnacl#95]
After upgrading from 1.5.0 to 1.5.1, I'm getting the following error:

```
  File "/usr/local/lib/python3.5/site-packages/libnacl/__init__.py", line 105, in <module>
    crypto_box_SEALBYTES = nacl.crypto_box_sealbytes()
  File "/usr/local/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libsodium.so: undefined symbol: crypto_box_sealbytes
```

I'm using `libsodium-dev=1.0.0-1` from apt-get

**Comment by whs** [comment]
It seems that sealed box support was added in [libsodium 1.0.3](https://github.com/jedisct1/libsodium/blob/master/ChangeLog#L197).

@thatch45, What should we do in this case?

1. Update the changelog to mention the requirement bump
2. Make `crypto_box_SEALBYTES` lazily initiated (Is that possible? Maybe try to detect version and initialize accordingly?)
2. Move that constant to the sealed box file

@petebrowne In my use case (My app is in python:3.6 based Docker container), currently I ship a custom built libsodium. You can find my build script at https://gist.github.com/whs/4e90f2cdff9910c042024477829940dd . The script tries to detect system libsodium first (which in my container I don't install any), then install the file from `gs/libsodium.so.18.2.0` to system location. (Obviously requires root). I've attached my current libsodium.so file as well.

You can use this as a workaround until we fixed this issue in case you need sealed box (or just downgrade for now if you don't).

**Comment by petebrowne** [comment]
Thanks for following up so quickly - We're not using any of the newer features of libsodium, so downgrading to 1.5.0 works for me.

**Comment by thatch45** [comment]
This should be an easy problem to fix, we wrap the module level sealbox refs tin try/except blocks, then set a global HAS_SEALBOX variable, then in the function check the variable and rise an exception if the variable is not available. I will get a PR and a release in shortly

**Comment by thatch45** [comment]
@petebrowne could I persuade you to try out this patch on 1.5.1 to see if it resolves your issue?
https://github.com/saltstack/libnacl/pull/96

**Comment by thatch45** [comment]
Reported as resolved
